name: zippo_app
description: A new Flutter project.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_picker: ^0.4.12+1
  flutter_launcher_icons: ^0.7.0
  path_provider: ^0.4.1
  flashlight: 
    path: C:\Users\Colin Poirier\Documents\flashlight

flutter_icons:
  image_path: "assets/ic_launcher_2_round.png"
  andaptive_icon_background: "607d8b"
  adaptive_icon_foreground: "assets/ic_launcher_2_round.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
     - assets/cage.png
     - assets/bottom.png
     - assets/top.png
     - assets/Zippo_Aperto.png
     - assets/download.jpeg
     - assets/wheel.png
     - assets/images/firesheet.png
     - assets/animations/flame.flr
     - assets/ic_launcher_2.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
